name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Format
        run: cargo fmt --all --check
      - name: Test all targets
        run: cargo test --all-targets
      - name: Build docs
        run: cargo doc --workspace --no-deps
      - name: Build release examples
        run: cargo build --workspace --examples --release
